<h2 class="text-center">Modul Lengkap untuk Menjalankan Aplikasi PHP Anda.</h2>
<div class="d-flex justify-content-between">
    <ul>
        <li>IcePHP</li>
        <li>apc</li>
        <li>apcu</li>
        <li>apm</li>
        <li>ares</li>
        <li>bcmath</li>
        <li>bcompiler</li>
        <li>big_int</li>
        <li>bitset</li>
        <li>bloomy</li>
        <li>bz2_filter</li>
        <li>clamav</li>
        <li>coin_acceptor</li>
        <li>crack</li>
        <li>dba</li>
    </ul>
    <ul>
        <li>IcePHP</li>
        <li>apc</li>
        <li>apcu</li>
        <li>apm</li>
        <li>ares</li>
        <li>bcmath</li>
        <li>bcompiler</li>
        <li>big_int</li>
        <li>bitset</li>
        <li>bloomy</li>
        <li>bz2_filter</li>
        <li>clamav</li>
        <li>coin_acceptor</li>
        <li>crack</li>
        <li>dba</li>
    </ul>
    <ul>
        <li>IcePHP</li>
        <li>apc</li>
        <li>apcu</li>
        <li>apm</li>
        <li>ares</li>
        <li>bcmath</li>
        <li>bcompiler</li>
        <li>big_int</li>
        <li>bitset</li>
        <li>bloomy</li>
        <li>bz2_filter</li>
        <li>clamav</li>
        <li>coin_acceptor</li>
        <li>crack</li>
        <li>dba</li>
    </ul>
    <ul>
        <li>IcePHP</li>
        <li>apc</li>
        <li>apcu</li>
        <li>apm</li>
        <li>ares</li>
        <li>bcmath</li>
        <li>bcompiler</li>
        <li>big_int</li>
        <li>bitset</li>
        <li>bloomy</li>
        <li>bz2_filter</li>
        <li>clamav</li>
        <li>coin_acceptor</li>
        <li>crack</li>
        <li>dba</li>
    </ul>
</div>
<div class="d-flex justify-content-center">
    <button type="button" class="btn btn-outline-primary rounded-pill">SELENGKAPNYA</button>
</div>

